### ISSUE TITLE
生成的都是噪点图

### ISSUE THREAD

**Issue by TimeWings** [7eu7d7/DreamArtist-stable-diffusion#1]
我clone repo之后，把models文件夹复制进去，不管是txt2img还是img2img，跑出来的都是噪点图
中途还报了缺少sklearn模块的错误，不过我自己解决了，不知道有没有影响

![image](https://user-images.githubusercontent.com/27570229/196032688-a1219523-e0b1-45eb-a479-4fa109059e0a.png)

**Comment by sotokisehiro** [comment]
I'm having a similar issue in my environment.
(There is no problem with the AUTOMATIC1111 version)

**Comment by JC-Array** [comment]
I was able to replicate the results for this image: 
https://github.com/7eu7d7/APT-stable-diffusion-auto-prompt/blob/master/imgs/p1.png?raw=true

By copying the image into PNG Info here is the following parameters:
masterpiece, best quality, ptun-d
Negative prompt: ptun-d-uc, lowres, bad anatomy, bad hands, text, error, missing fingers, extra fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
Steps: 25, Sampler: Euler a, CFG scale: 7, Seed: 1316503418, Size: 768x512, Model hash: e6e8e1fc


Running this on AUTOMATIC1111's version I get the following image:
![00318-1316503418-masterpiece, best quality, ptun-d](https://user-images.githubusercontent.com/44535867/196062927-f896adda-b948-4207-98a4-96614ddbefb0.png)

However I was about to recreate it properly on this repo and product similar images.

If you are getting a static image check that your using the correct model.  Hash: e6e8e1fc.  Aka NAI's animefull-latest.

**Comment by MEIZU16** [comment]
同样的问题

**Comment by 7eu7d7** [comment]
我的模型是在hq done上练的，如果用不一样的可能出bug

**Comment by zozyo** [comment]
# sha256sum novelaileakpt2/random_stableckpt/animefullhq-done/model.ckpt 
a7529df02340e5b4c3870c894c1ae84f22ea7b37fd0633e5bacfad9618228032  novelaileakpt2/random_stableckpt/animefullhq-done/model.ckpt
# sha256sum novelaileakpt2/random_stableckpt/animefull-latest/model.ckpt 
a7529df02340e5b4c3870c894c1ae84f22ea7b37fd0633e5bacfad9618228032  novelaileakpt2/random_stableckpt/animefull-latest/model.ckpt

**Comment by fenglindubu** [comment]
ModuleNotFoundError: No module named 'sklearn'
pip3 install scikit-learn我运行这个还是报错啊，请问怎么解决的

**Comment by TimeWings** [comment]
> 我的模型是在hq done上练的，如果用不一样的可能出bug

我换成part2的animefullhq-done成功出图了，出一次图后再换成其他模型也正常出图了，神奇

**Comment by sotokisehiro** [comment]
> 我的模型是在hq done上练的，如果用不一样的可能出bug

Thank you for the advice.
After changing the model, I was able to confirm that the image can be generated.
I'm trying "Prompt Thuing" and it works great!

![スクリーンショット 2022-10-18 074122](https://user-images.githubusercontent.com/101786086/196298374-a59a623e-b1e5-4d81-9fbb-1db86f2e6142.jpg)
