### ISSUE TITLE
how many steps are needed for good results

### ISSUE THREAD

**Issue by loboere** [7eu7d7/DreamArtist-stable-diffusion#10]
how many steps are needed for good results

**Comment by sonicviz** [comment]
Yes, the instructions cut off and leave out the rest of the key training settings.

Can you please elaborate on the full set of parameters for the training? thanks!

**Comment by m11925** [comment]
It would helpful if the configurations for the examples were provided, along with the particular model used and any SD-UI wide settings that could impact results.
