### ISSUE TITLE
dreambooth gives better rresults, faster

### ISSUE THREAD

**Issue by demirklvc** [7eu7d7/DreamArtist-stable-diffusion#12]
hello! tested on 3090 ti gpu-i get better results with dreambooth in 10 minutes than with this in one hour. any advise for training, naming or something? best wishes

**Comment by m11925** [comment]
@demirklvc documentation in this repo is out of date, see https://github.com/7eu7d7/DreamArtist-sd-webui-extension for examples.

**Comment by 7eu7d7** [comment]
The original instructions are quite rough and you may not use DreamArtist correctly. You can use it following the (new instructions)[https://github.com/7eu7d7/DreamArtist-sd-webui-extension#training-and-usage].
