### ISSUE TITLE
Has anyone gotten the extension to actually work yet?

### ISSUE THREAD

**Issue by devNegative-asm** [7eu7d7/DreamArtist-stable-diffusion#13]
Everyone I asked on the SD discord said the results looked nothing like the training image. The results in the readme look great so I'm left wondering what went wrong? Did they use a bad learning rate? step count? Is there something weird with sample images that doesn't apply when using the embeddings in a prompt normally? I really want to try this, but I fear it will be a waste of time if I don't know the right way to use it

**Comment by Raz0rStorm** [comment]
I feel the author really needs to make a throughout guide, so far mine are all failures

**Comment by 7eu7d7** [comment]
Now updated with more detailed usage instructions, you can refer to [this](https://github.com/7eu7d7/DreamArtist-sd-webui-extension#training-and-usage).
