### ISSUE TITLE
Not getting desired result, loss shrinking during ~400 steps

### ISSUE THREAD

**Issue by Raz0rStorm** [7eu7d7/DreamArtist-stable-diffusion#14]
Tried many times training, but still no good result
Like in the first ~400steps it seems like it's going somewhere with a loss ~0.3
but after that, the loss suddenly shrink to ~0.05 and become stagnated
also I don't know how to use both the convnext model?
tried lr from 0.01-0.0025 cfg 3-5 without success
Is there something I've done wrong?
Using Anything-V3.0-pruned.ckpt, setting:
{
    "bs": 1,
    "cfg": 3.0,
    "lr": "0.0025",
    "neg": true,
    "neg_lr_w": 1,
    "prompt_len": [
        6,
        768
    ],
    "prompt_len_neg": [
        12,
        768
    ],
    "rec": true,
    "rec_loss_w": 1,
    "size": 384
}
Input image:
![00012-0-eaf9d358dd2525db5d59fdc28a0f6757](https://user-images.githubusercontent.com/95212158/202381993-1c0ee094-b2af-4886-9b66-42b536920b51.png)
Output after 5000 steps:
![00001-993531467](https://user-images.githubusercontent.com/95212158/202382154-55884c65-826b-47ec-aade-3899e58361a4.png)
[prompt_tuning_loss.csv](https://github.com/7eu7d7/DreamArtist-stable-diffusion/files/10028931/prompt_tuning_loss.csv)

**Comment by 7eu7d7** [comment]
The original instructions are quite rough and you may not use DreamArtist correctly. You can use it following the [new instructions](https://github.com/7eu7d7/DreamArtist-sd-webui-extension#training-and-usage).

**Comment by Raz0rStorm** [comment]
> The original instructions are quite rough and you may not use DreamArtist correctly. You can use it following the [new instructions](https://github.com/7eu7d7/DreamArtist-sd-webui-extension#training-and-usage).

the new instruction does not mention the convnext classifier, is it better not to use them? Or how to use checkpoint-best_t5.pth and convnext_xlarge_22k_1k_384_ema.pth together?

**Comment by 7eu7d7** [comment]
> 还有新教程里没写convnext相关的信息

convnext可以参考我另外的[AI爬虫](https://github.com/7eu7d7/pixiv_AI_crawler)，按这个方式练的就可以用，你喜欢的放类别1
