### ISSUE TITLE
做成webui插件/Make this an extension to stable-diffusion-webui

### ISSUE THREAD

**Issue by sgsdxzy** [7eu7d7/DreamArtist-stable-diffusion#4]
最新版的webui支持插件形式了，可以考虑做成插件？这样不需要merge，可以立即使用master的最新功能，并且项目能减小很多，可维护性更好。

The advantages of making this an extension instead of a standalone repo/branch:

1. no merging require.
2. keep up with the latest webui/master.
3. smaller code base.

**Comment by sotokisehiro** [comment]
我同意。
如果可能，请使用扩展来实现它。
（机器翻译）
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2945

**Comment by AiMiDi** [comment]
I'm trying to make it an extension:
我在尝试把它制作成扩展了：

https://github.com/AiMiDi/stable-diffusion-webui-advance-prompt-tuning

**Comment by 7eu7d7** [comment]
最新版已经做成插件了 https://github.com/7eu7d7/DreamArtist-sd-webui-extension
