### ISSUE TITLE
What are the embeddings released?

### ISSUE THREAD

**Issue by aliencaocao** [7eu7d7/DreamArtist-stable-diffusion#6]
I see there is a embedding.zip in the release page. The file names inside are mysterious, I cannot tell which embedding is for what. Do you have a list of them? Thanks

![image](https://user-images.githubusercontent.com/20109683/201474863-ba19a407-4674-43be-b357-094b9744dd34.png)

**Comment by 7eu7d7** [comment]
Descriptions have been added in the new version

**Comment by aliencaocao** [comment]
Hi i saw the updated ones, but they are not the same as the V1 release. May I know what are the weights in the V1 for?
V1 contains the files in my original post.
