### ISSUE TITLE
extension does not work

### ISSUE THREAD

**Issue by loboere** [7eu7d7/DreamArtist-stable-diffusion#9]
install the extension but i can't write anything , only name

![image](https://user-images.githubusercontent.com/15265895/201579974-ef150bcf-9b93-434c-b143-921252368eac.png)

**Comment by royherma** [comment]
@loboere did you get it to work? I tried installing via extensions and installation looks good, but do not see the "Dreamartist" tab under the "Train" tab... any ideas?

**Comment by royherma** [comment]
<img width="878" alt="Screenshot 2022-11-14 at 13 00 58" src="https://user-images.githubusercontent.com/3466248/201643829-5f599270-60b0-4df1-a016-cdc44c5a86f2.png">

@loboere i have it installed as you can see

**Comment by tsukimiya** [comment]
@loboere 
The same situation occurred when the extension setup.py was not executed.
After git clone, try running launch.py in WEB UI.

**Comment by 7eu7d7** [comment]
The old version of the DreamArtist was in the Train Tab, the new version is separate out.
